### ISSUE TITLE
convert Chinese commas to -

### ISSUE THREAD

**Issue by leosin** [senlin/pinyin-slugs#13]
can you add a function that can convert Chinese commas“，” to "-"

**Comment by senlin** [comment]
Hi Michael, thanks for your suggestion.

To be honest at the moment I lack the time to actively work on this plugin, but I will label it as a feature request and if anyone feels inclined to have a go at it, then I welcome PR's!

Thanks,
Pieter

**Comment by senlin** [comment]
Closing this as no further news or contributions.
