### ISSUE TITLE
Can add media or other upload type file, filename Chinese conversion? For example, xxxxxxxxxxxxx.mp3, prefix name XXXXXXXXXXXXXXX Chinese conversion

### ISSUE THREAD

**Issue by Starbear3** [senlin/pinyin-slugs#14]
Can add media or other upload type file, filename Chinese conversion?
For example, xxxxxxxxxxxxx.mp3, prefix name XXXXXXXXXXXXXXX Chinese conversion

**Comment by senlin** [comment]
No, file name conversions won't work.

**Comment by Starbear3** [comment]
Well, forgive me for asking.I understand that there are other bugs if I switch to Chinese or something like that, but I'd still like to see file name conversions

**Comment by senlin** [comment]
> Well, forgive me for asking.

Of course you can ask, no problem.

> I understand that there are other bugs if I switch to Chinese

Yeah I'm not sure I even understand that bug, I used Google Translate, but it leaves out a lot of details and context

> I'd still like to see file name conversions

Well, if you really want it, then I am looking forward receiving your PR :)

**Comment by senlin** [comment]
Closing this now, feel free to re-open if you have relevant PR or other contribution
