### ISSUE TITLE
Pynyin slugs URL written together without hyphens

### ISSUE THREAD

**Issue by stolyarov-p** [senlin/pinyin-slugs#15]
Hello. I create my post in chinese on WP 5+, my header is in Chinese. 王巨亭, for example. But when i save the post, i have URL looks like _wangjuting_, not like _wang-ju-ting_.

How can i create URLs with hyphen, when use your plugin,

Thank you for your answer.

**Comment by senlin** [comment]
Hi, your question has been described in the README file:

> Search engines such as Baidu obviously cannot make much of the first slug, but they can handle pinyin perfectly, especially when it is written as one long string without hyphens or underscores.
> 
> So instead of transforming "中国" into two separate words divided by a hyphen or an underscore (the original plugin has this as options), it is best transformed into "zhongguo". The only option Pinyin Slugs therefore has left is the length that you can limit to an x amount of letters. The default is 100, which should be plenty for most.

Trust that answers your question.
