### ISSUE TITLE
How to change my past passages into pinyin?

### ISSUE THREAD

**Issue by youthriverside** [senlin/pinyin-slugs#17]
![image](https://user-images.githubusercontent.com/63176620/104416664-23037900-55af-11eb-9fa8-7eea7931e451.png)
I have about 166 passages,Are there any easy ways to change their names into Pinyin?

**Comment by senlin** [comment]
Hi, the plugin clearly states that it can only change the slugs for new content, **not for existing content**.

The easiest way will be to sit down for it and do the grind :)
