### ISSUE TITLE
 Alias length Invalid setting Does not work

### ISSUE THREAD

**Issue by zhouLife** [senlin/pinyin-slugs#19]
Alias length Invalid setting Does not work
别名长度 设置无效 不起作用
![E9ow0g](https://github.com/senlin/pinyin-slugs/assets/47948826/7fc64e85-700b-4184-b633-592f9c9f0b27)
![llSy5V](https://github.com/senlin/pinyin-slugs/assets/47948826/942ee1ef-829b-4668-b6ad-4c4d2f6db23e)

**Comment by senlin** [comment]
cannot replicate, works exactly as advertised for me.
most likely edge case?

**Comment by zhouLife** [comment]
Deleted (4K, 3A, 44A, 55A) Same effect.
No matter how many characters are set, it will only be the default 100
![chrome_kKIJI74OwD](https://github.com/senlin/pinyin-slugs/assets/47948826/b39897b7-f334-4846-965b-5ee44a435609)

**Comment by senlin** [comment]
Ah I see, fixed in v2.3.0; thank for reporting!
