### ISSUE TITLE
Replace spaces with dashes

### ISSUE THREAD

**Issue by nhimthaoan** [senlin/pinyin-slugs#23]
Hello, in version 2.3.1 the plugin removed spaces instead of converting them to dashes.
This makes the slug ugly, can you return it to the way it was before, replace the spaces with dashes.

loremipsumdolorsitamet
lorem-ipsum-dolor-sit-amet

**Comment by senlin** [comment]
I'm not sure I understand? With the plugin installed characters are changed to Pinyin, so how can an old URL contain Chinese characters?

**Comment by senlin** [comment]
Also I am unable to replicate that

**Comment by senlin** [comment]
see [this screencast](https://monosnap.com/file/3qFeJBoldCb3Dbd947BA3JjedT0hu4) to show that Chinese characters in URLs remain and there are no 404's.

**Comment by senlin** [comment]
released v2.3.2 that fixes the reported issue, closing this thread

(the 404 issue is not related and must have a different source)
